language: node_js
node_js:
  - "9"
  - "8"
  - "7"
  - "6"
before_script:
  - "npm run build-css"
cache:
  directories:
  - node_modules
  - packages/create-react-app/node_modules
  - packages/react-scripts/node_modules
